version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: devopsdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"